C     *** CIT AIRSHED MODEL ***
C     INCLUDE FILE TO DEFINE MAXIMUM ARRAY SIZES
C     REVISED VERSION BY ROBERT HARLEY (AUGUST 1992) FOR
C     SAPRC MECHANISM COMPILER
C
C     CAUTIONARY NOTES:  IF CHANGES ARE MADE TO THIS FILE,
C     BE SURE TO CHECK THAT THE DEFINITION OF LBIGRC IS REVISED
C     (IF NGMX OR NGMY IS CHANGED).  ALSO, IF NEMAX OR NIMAX 
C     ARE CHANGED, VERIFY THE NEW DEFINITION OF LWORK.
C
C     NOTE:  THIS FILE MUST BE PRECEDED BY THE SAPRC MECHANISMS 
C            INCLUDE FILE "MODLSPC.H"  
C
C     NSMAX  - MAXIMUM NUMBER OF CHEMICAL SPECIES (active only)
C     NIMAX  - MAXIMUM NUMBER OF INITIAL CONDITION SPECIES
C     NEMAX  - MAXIMUM NUMBER OF EMITTED SPECIES 
C     NLUMAX - MAXIMUM NUMBER OF LAND USE TYPES
C     NRMAX  - MAXIMUM NUMBER OF CHEMICAL REACTIONS
C     NPMAX  - MAXIMUM NUMBER OF POINT SOURCES   
C     LWORK  - LENGTH OF THE WORK VECTOR
C
      INTEGER NSMAX
      PARAMETER (NSMAX = maxact)
CAliA      PARAMETER (NIMAX = 17)
CAliA      PARAMETER (NEMAX = 75)
CAliA      PARAMETER (NLUMAX = 32)             
CAliA      PARAMETER (NRMAX = maxrxn)
CAliA      PARAMETER (NPMAX = 900)
C
C     MAXIMUM NUMBER OF GRID SQUARES (DO NOT SET NGMZ LARGER THAN 10)
C     NGMX   - MAXIMUM NUMBER OF MASTER GRID CELLS IN X DIRECTION
C     NGMY   - MAXIMUM NUMBER OF MASTER GRID CELLS IN Y DIRECTION
C     NGMZ   - MAXIMUM NUMBER OF VERTICAL COMPUTATIONAL CELLS
C     LBIGRC - SET TO LARGER OF NGMX AND NGMY
C
      INTEGER NGMX, NGMY, NGMZ
c      PARAMETER (NGMX = 80, NGMY = 30, NGMZ = 7)
      PARAMETER (NGMX = 1, NGMY = 1, NGMZ = 1)
CAliA      PARAMETER (LBIGRC = NGMX)
C
C     DEFINE LWORK USING THE LARGER OF NEMAX AND NIMAX
C
CAliA      PARAMETER (LWORK = NGMX * NGMY * NEMAX)
C
C     DERIVED PARAMETERS FOR SCALAR AND VECTOR ARRAY DIMENSIONS
C
C     LSCAL  - ELEMENTS IN A SCALAR (SURFACE LEVEL ONLY) ARRAY
C     LWIND  - ELEMENTS IN THE 3D WIND FIELD ARRAY
C     LAREAS - ELEMENTS IN GROUND-LEVEL EMISSIONS ARRAY
C     LC     - ELEMENTS IN SPECIES CONCENTRATION ARRAY
C     LIC    - ELEMENTS IN INITIAL CONDITION CONCENTRATION ARRAY
C     LAVG   - ELEMENTS IN HOURLY AVERAGE GROUND-LEVEL CONC ARRAY
C
c      PARAMETER (LSCAL  =  NGMX * NGMY)
c      PARAMETER (LAREAS =  NGMX * NGMY * NEMAX)
c      PARAMETER (LWIND  =  NGMX * NGMY * NGMZ)
c      PARAMETER (LC     =  NGMX * NGMY * NGMZ * NSMAX)
c      PARAMETER (LIC    =  NGMX * NGMY * NGMZ * NIMAX)
c      PARAMETER (LAVG   =  NGMX * NGMY * NSMAX)
c      PARAMETER (LSCAL  =  720) ! for use with region.saprc
CAliA      PARAMETER (LSCAL  =  1000) ! for use with region.big
CAliA      PARAMETER (LAREAS =  LSCAL * NEMAX)
CAliA      PARAMETER (LWIND  =  LSCAL * NGMZ)
CAliA      PARAMETER (LC     =  LSCAL * NGMZ * NSMAX)
CAliA      PARAMETER (LIC    =  LSCAL * NGMZ * NIMAX)
CAliA      PARAMETER (LAVG   =  LSCAL * NSMAX)
C
C     DERIVED PARAMETERS FOR BOUNDARY CONDITION ARRAYS
C
CAliA      PARAMETER (LBR   = NGMY * NGMZ * NSMAX)
CAliA      PARAMETER (LBRIC = NGMY * NGMZ * NIMAX)
CAliA      PARAMETER (LBC   = NGMX * NGMZ * NSMAX)
CAliA      PARAMETER (LBCIC = NGMX * NGMZ * NIMAX)
C
C     TOTAL NUMBER OF STORAGE LOCATIONS REQUIRED FOR
C     A VERTICAL COLUMN OF SPECIES CONCENTRATIONS
C
      INTEGER LCOLSP
      PARAMETER (LCOLSP = NSMAX * NGMZ)
CAliA      PARAMETER (LCOLSP2 = NSMAX * (NGMZ+1))
C
C     DIMENSIONS OF THE AEROSOL ARRAY WHEN IT IS NOT STORED LINEARLY
C
C     NTYPE_SOURCE - MAX NUMBER OF PARTICLE SOURCES
C     NTYPE        - MAX NUMBER OF PARTICLE TYPES (INCLUDING ICS/BCS/SOURCES)
C     NTIME        - MAX NUMBER OF PARTICLE TIME CUTS
C     NBLIM        - NUMBER OF DISCRETE PARTICLE SIZES
C     NALIM        - NUMBER OF AEROSOL CHEMICAL SPECIES
C     NAEMIT       - NUMBER OF PRIMARY AEROSOL CHEMICAL SPECIES
C     NAEQB        - NUMBER OF AEROSOL CHEMICAL COMPONENTS IN EQBM CALCULATION
C     NGLIM        - NUMBER OF GAS VARIABLES IN KINETIC MECHANISM
C     NSAVEMAX     - MAX NUMBER OF PARTICLE SAVE LOCATIONS
C     RMAXF        - MAXIMUM FILE SIZE SUPPORTED BY HOST OPERATING SYSTEM (GB)
C
      INTEGER NTYPE_SOURCE, NTYPE
c      PARAMETER (NTYPE_SOURCE = 9) 
c      PARAMETER (NTYPE = 10)
      PARAMETER (NTYPE=1)
CAliA      PARAMETER (NTYPE_SOURCE=9)

C MAX NUMBER OF GAS SOURCE TYPES
CAliA      PARAMETER (MAXTYPEG = 8)
CAliA      PARAMETER (NTYPEG_SOURCE = 8)

      INTEGER NBLIM, NTIME
      PARAMETER (NTIME = 1)
      PARAMETER (NBLIM = 1)

c changed by Qi Ying, Feb. 2003
c changed to hold expanded gas phase chemistry
      INTEGER NALIM
c      PARAMETER (NALIM = 54)
c      PARAMETER (NALIM = 48)
      PARAMETER (NALIM = 0)
c changed to hold expanded gas phase chemistry      

CAliA      PARAMETER (NAEMIT = 28)
CAliA      PARAMETER (NAEQB = 16) 

c changed to hold expanded gas phase chemistry
      INTEGER NGLIM
c      PARAMETER (NGLIM = 99)
      PARAMETER (NGLIM = 306)
c changed to hold expanded gas phase chemistry

      INTEGER NCZ, NPZ
      PARAMETER (NCZ = MAXCON*NGMZ)
      PARAMETER (NPZ = MAXSTS*NGMZ)
CAliA      PARAMETER (NSAVEMAX = 10)
CAliA      PARAMETER (RMAXF = 2.)

c advection solver option, Qi Ying (Feb. 2003)
c IADVECT=1       ASD SOLVER
c IADVECT=2       FINITE ELEMENT SOLVER
CAliA      PARAMETER (IADVECT = 1)
c advection solver option


C
C     DERIVED PARAMETERS FOR SIZING THE AEROSOL ARRAYS
C
CAliA      parameter (nazp = ngmz*nalim)
      INTEGER NVECT
      parameter (nvect = ntype*ntime*nblim)
c use the first line for external mixture model
c use the second line for internal mixture model
      INTEGER MAXRXNZ, nd2
c      parameter (nd2 = nvect*nalim + nglim)
      parameter (nd2 = 500)
      parameter (maxrxnz = maxrxn*ngmz)
CAliA      parameter (nd3 = lcolsp+ntype*2+nvect*ngmz*(nalim+6)+4)
CAliA      parameter (nd4 = lbigrc*nalim*nblim + 4)
